### Create new report
POST http://localhost:3000/reports/1
content-type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 1980,
  "mileage": 100000,
  "longitude": 0,
  "latitude": 0,
  "price": 500000
}

