# Uses extensions REST client to replace postman
### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "royer@gmail.com",
  "password": "royerdev"
}
# {
#   "email": "asdf@gmail.com",
#   "password": "asdlfkj"
# }

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users
GET http://localhost:3000/auth
### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@gmail.com

### Delete a particular user
Delete http://localhost:3000/auth/1

### Update a user information
Put http://localhost:3000/auth/2
content-type: application/json

{
  "email": "royer@gmail.com",
  "password": "asdlfkj"
}